# Generated by Django 5.1.3 on 2024-11-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_size_stock_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
        ),
    ]
