# Generated by Django 5.1.3 on 2024-12-10 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Types',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.types'),
        ),
    ]
