# Generated by Django 5.1.3 on 2024-12-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_types_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applied_offer',
            field=models.CharField(blank=True, choices=[('category', 'Category Offer'), ('type', 'Type Offer'), ('product', 'Product Offer'), ('none', 'No Offer')], max_length=50, null=True),
        ),
    ]
