# Generated by Django 5.1.3 on 2024-12-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_used',
            field=models.BooleanField(default=False),
        ),
    ]
