# Generated by Django 5.1.3 on 2024-11-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_remove_size_stock_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount in percentage (e.g. 20 for 20%)', max_digits=5)),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(help_text='Start date of the offer')),
                ('end_date', models.DateTimeField(help_text='End date of the offer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.product')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
