# Generated by Django 5.1.3 on 2024-11-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_coupons', '0002_offer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
