# Generated by Django 5.1.3 on 2024-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers_coupons', '0003_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.PositiveIntegerField()),
                ('status', models.CharField(default='listed', max_length=10)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
