# Generated by Django 5.1.3 on 2024-11-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_coupons', '0008_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
